### ISSUE TITLE
Static Positioning?

### ISSUE THREAD

**Issue by iBotPeaches** [sourcetoad/add-badge#10]
In testing with newer Android applications that leverage the anydpi pattern of:

```xml
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
  <background android:drawable="@mipmap/ic_launcher_background"/>
  <foreground android:drawable="@mipmap/ic_launcher_foreground"/>
  <monochrome android:drawable="@mipmap/ic_launcher_monochrome"/>
</adaptive-icon>
```

We find we have a few possibilities for badging. If we badge the background - it looks elegant, but then the foreground lays on top of the badge and looks off. This means I believe our only option is badging the foreground. However, in the case of this client application where the client logo is a single "P" - the badged icon struggles to scale/fit on the various iterations of it.

I was hoping to just say like - "north, 2px from top" so it could sit on top of the image of the foreground. Want to open this to discuss some options or ways I could badge this efficiently.

**Comment by erik-perri** [comment]
One of the earlier implementations supported changing the offset but it ended up being removed over time as the automatic detection got ironed out. It was also a little awkward since it had to scale the adjustment for each size and some sizes might not have wanted adjustments. That might not be as much of a concern if we add a manual positioning rather than adjusting the dynamic offset.

I do wonder if we'll want to change how we're configuring it though.  If we end up needing to support multiple icon types with different options for them, it might make more sense to use a configuration file rather than calling the command with different switches and blobs.  I will do some testing of a manual position option to see if it causes any issues with other icon types. I remember having some foreground images getting cropped circularly in the past but I don't remember the specifics.

**Comment by erik-perri** [comment]
Do you have a preference on how we specify the position?

Based on your comment and after looking over the code, I saw an easy path for a `--position=X` where X is a percent of the image size and it places the badge at the angle of the gravity at that position. When specified we could use it rather than the "inside circle" calculation we do. I am not sure how useful it would be though since we'd be limited by the gravity angles and half would be duplicates (North and South would be functionally the same, just with inverted percent values).

If we want more control, we could take X and Y as options and just use gravity to orient the badge.  I could also see wanting full control and just have `gravity` be the automatic path, with new `position` and `rotation` options for the manual positioning.

**Comment by iBotPeaches** [comment]
The `--position` could work because it could be a small percentage to allow just roughly bubbling the badge on the outer edge even if the image/icon is quite smaller to account for the background.

**Comment by erik-perri** [comment]
I added the ability to set the position on the gravity's axis, and the ability to set the position's X and Y manually in #12 ([preview](https://github.com/sourcetoad/add-badge/blob/static-positioning/SAMPLES.md#position)).
